INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('The Shawshank Redemption', 1994, 'A', '142 min', 'Drama', 9.3, 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 80, 'Frank Darabont', 'Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler', 2343110, 28341469);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('The Godfather', 1972, 'A', '175 min', 'Crime, Drama', 9.2, 'An organized crime dynasty''s aging patriarch transfers control of his clandestine empire to his reluctant son.', 100, 'Francis Ford Coppola', 'Marlon Brando', 'Al Pacino', 'James Caan', 'Diane Keaton', 1620367, 134966411);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('The Dark Knight', 2008, 'UA', '152 min', 'Action, Crime, Drama', 9, 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 84, 'Christopher Nolan', 'Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine', 2303232, 534858444);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('The Godfather: Part II', 1974, 'A', '202 min', 'Crime, Drama', 9, 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.', 90, 'Francis Ford Coppola', 'Al Pacino', 'Robert De Niro', 'Robert Duvall', 'Diane Keaton', 1129952, 57300000);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('12 Angry Men', 1957, 'U', '96 min', 'Crime, Drama', 9, 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.', 96, 'Sidney Lumet', 'Henry Fonda', 'Lee J. Cobb', 'Martin Balsam', 'John Fiedler', 689845, 4360000);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('The Lord of the Rings: The Return of the King', 2003, 'U', '201 min', 'Action, Adventure, Drama', 8.9, 'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', 94, 'Peter Jackson', 'Elijah Wood', 'Viggo Mortensen', 'Ian McKellen', 'Orlando Bloom', 1642758, 377845905);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('Pulp Fiction', 1994, 'A', '154 min', 'Crime, Drama', 8.9, 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 94, 'Quentin Tarantino', 'John Travolta', 'Uma Thurman', 'Samuel L. Jackson', 'Bruce Willis', 1826188, 107928762);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('Schindler''s List', 1993, 'A', '195 min', 'Biography, Drama, History', 8.9, 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.', 94, 'Steven Spielberg', 'Liam Neeson', 'Ralph Fiennes', 'Ben Kingsley', 'Caroline Goodall', 1213505, 96898818);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('Inception', 2010, 'UA', '148 min', 'Action, Adventure, Sci-Fi', 8.8, 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.', 74, 'Christopher Nolan', 'Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy', 2100071, 292576195);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('Fight Club', 1999, 'A', '139 min', 'Drama', 8.8, 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much, much more.', 66, 'David Fincher', 'Brad Pitt', 'Edward Norton', 'Meat Loaf', 'Zach Grenier', 1845017, 100853753);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('The Good, the Bad and the Ugly', 1966, 'UA', '161 min', 'Adventure, Western', 8.8, 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.', 90, 'Sergio Leone', 'Clint Eastwood', 'Eli Wallach', 'Lee Van Cleef', 'Aldo Giuffrè', 717097, 25150000);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('The Lord of the Rings: The Fellowship of the Ring', 2001, 'U', '178 min', 'Action, Adventure, Drama', 8.8, 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', 92, 'Peter Jackson', 'Elijah Wood', 'Ian McKellen', 'Orlando Bloom', 'Sean Bean', 1768366, 315710750);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('Forrest Gump', 1994, 'A', '142 min', 'Drama, Romance', 8.8, 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.', 82, 'Robert Zemeckis', 'Tom Hanks', 'Robin Wright', 'Gary Sinise', 'Sally Field', 2012971, 330252182);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('2001: A Space Odyssey', 1968, 'G', '149 min', 'Adventure, Sci-Fi', 8.3, 'After discovering a mysterious artifact buried beneath the lunar surface, mankind sets off on a quest to find its origins with help from intelligent supercomputer HAL 9000.', 84, 'Stanley Kubrick', 'Keir Dullea', 'Gary Lockwood', 'William Sylvester', 'Daniel Richter', 606822, 56800416);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('Vertigo', 1958, 'PG', '128 min', 'Mystery, Romance, Thriller', 8.3, 'A former police detective juggles wrestling with his personal demons and becoming obsessed with the hauntingly beautiful woman he has been hired to trail, who may be deeply disturbed.', 100, 'Alfred Hitchcock', 'James Stewart', 'Kim Novak', 'Barbara Bel Geddes', 'Tom Helmore', 383826, 7634748);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('The Lion King', 1994, 'G', '88 min', 'Animation, Adventure, Drama', 8.5, 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', 88, 'Roger Allers', 'Matthew Broderick', 'Jeremy Irons', 'James Earl Jones', 'Whoopi Goldberg', 939607, 422783777);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('Rear Window', 1954, 'PG', '112 min', 'Mystery, Thriller', 8.4, 'A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.', 100, 'Alfred Hitchcock', 'James Stewart', 'Grace Kelly', 'Wendell Corey', 'Thelma Ritter', 438681, 36764313);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('Alien', 1979, 'R', '117 min', 'Horror, Sci-Fi', 8.4, 'After a space merchant vessel receives an unknown transmission as a distress call, one of the crew is attacked by a mysterious lifeform, and they soon realize that its life cycle has merely begun.', 89, 'Ridley Scott', 'Sigourney Weaver', 'Tom Skerritt', 'John Hurt', 'Veronica Cartwright', 751736, 81285624);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('Apocalypse Now', 1979, 'R', '147 min', 'Drama, War', 8.4, 'A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.', 94, 'Francis Ford Coppola', 'Martin Sheen', 'Marlon Brando', 'Robert Duvall', 'Frederic Forrest', 630857, 83471511);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('Memento', 2000, 'R', '113 min', 'Mystery, Thriller', 8.4, 'A man with short-term memory loss attempts to track down his wife''s murderer.', 80, 'Christopher Nolan', 'Guy Pearce', 'Carrie-Anne Moss', 'Joe Pantoliano', 'Mark Boone Junior', 1146326, 25619180);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('Django Unchained', 2012, 'R', '165 min', 'Drama, Western', 8.4, 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation-owner in Mississippi.', 81, 'Quentin Tarantino', 'Jamie Foxx', 'Christoph Waltz', 'Leonardo DiCaprio', 'Kerry Washington', 1373510, 162805434);

INSERT INTO movie (title, released_year, certificate, runtime, genre, imdb_rating, overview, meta_score, director, actor1, actor2, actor3, actor4, number_of_votes, gross_income) VALUES ('The Lives of Others', 2006, 'R', '137 min', 'Drama, Mystery, Thriller', 8.4, 'In 1984 East Berlin, an agent of the secret police, conducting surveillance on a writer and his lover, finds himself becoming increasingly absorbed by their lives.', 89, 'Florian Henckel von Donnersmarck', 'Ulrich Mühe', 'Martina Gedeck', 'Sebastian Koch', 'Ulrich Tukur', 354466, 11309123);
